# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnhU01Su8iL7So-fftoPtiSqJ-JpvQbV
"""

import streamlit as st
import pandas as pd


st.header('Largest Of Three')

def user_input_features():
    num_1 = st.number_input("First Number",min_value=-20000000.0,max_value=20000000.0)
    num_2 = st.number_input("Second Number",min_value=-20000000.0,max_value=20000000.0)
    num_3 = st.number_input("Third Number",min_value=-20000000.0,max_value=20000000.0)

    return num_1,num_2,num_3

num_1,num_2,num_3 = user_input_features()

if(st.button('Find Largest')):
  st.subheader('Largest Of Three')
  st.write(max(num_1,num_2,num_3))
